In [1]:
import mdsine2 as md2
from mdsine2.names import STRNAMES
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
import os
import pandas as pd
from pathlib import Path
import matplotlib.cm as cm
import seaborn as sns

md2.visualization.set_perturbation_color('gray')
cols = [cm.tab10(i) for i in range(10)]
cols.append(cm.Set2(5))
cols.append(cm.Paired(4))

[DEBUG] Using default logger (stdout, stderr).


In [10]:
a = np.load('ecological-modeling/agglomeration.npy')
print(a.shape)
a

(12,)


array([0, 1, 1, 0, 0, 0, 1, 0, 2, 0, 1, 1])

In [11]:
b = np.load('ecological-modeling/coclusters.npy')
print(b.shape)
b

(12, 12)


array([[1.00000000e+00, 1.02315789e-02, 2.10526316e-04, 5.94442105e-01,
        6.49978947e-01, 5.76378947e-01, 1.63242105e-01, 6.55536842e-01,
        3.47242105e-01, 5.25221053e-01, 1.75157895e-02, 1.05263158e-03],
       [1.02315789e-02, 1.00000000e+00, 7.97136842e-01, 2.14315789e-02,
        2.18526316e-02, 1.14778947e-01, 6.90484211e-01, 9.17894737e-03,
        4.21515789e-01, 1.65894737e-01, 9.46863158e-01, 8.52715789e-01],
       [2.10526316e-04, 7.97136842e-01, 1.00000000e+00, 1.68421053e-04,
        1.09473684e-03, 4.44631579e-02, 5.10694737e-01, 1.68421053e-04,
        2.97136842e-01, 1.69600000e-01, 7.67536842e-01, 9.11663158e-01],
       [5.94442105e-01, 2.14315789e-02, 1.68421053e-04, 1.00000000e+00,
        5.85347368e-01, 5.19789474e-01, 1.63915789e-01, 6.10273684e-01,
        3.39157895e-01, 5.05978947e-01, 2.84631579e-02, 2.18947368e-03],
       [6.49978947e-01, 2.18526316e-02, 1.09473684e-03, 5.85347368e-01,
        1.00000000e+00, 6.04884211e-01, 1.74947368e-01, 6.41

In [12]:
c = np.load('ecological-modeling/growth.npy')
print(c.shape)
c

(95000, 12)


array([[0.39125439, 0.47544196, 1.05034057, ..., 0.1003174 , 0.46885109,
        0.9196258 ],
       [0.37506884, 0.50486112, 1.09992825, ..., 0.09458886, 0.50257143,
        1.0104328 ],
       [0.4237642 , 0.52326851, 1.04500143, ..., 0.08760232, 0.56126947,
        0.98179362],
       ...,
       [0.25385706, 0.38906655, 0.79647155, ..., 0.06880077, 0.44648599,
        0.4983478 ],
       [0.2544764 , 0.36763492, 0.75885963, ..., 0.1127858 , 0.43674699,
        0.54107895],
       [0.32711514, 0.41544659, 0.78545725, ..., 0.04739931, 0.39692692,
        0.5272253 ]])

In [23]:
c_mean = np.mean(c, axis=0)
print(c_mean.shape)
c_mean

(12,)


array([0.30397953, 0.51917356, 1.00535698, 0.63752321, 0.36283092,
       0.2488252 , 0.52109171, 0.49010655, 0.24344515, 0.0768812 ,
       0.50192556, 0.90942421])

In [13]:
d = np.load('ecological-modeling/interactions.npy')
print(d.shape)
d

(95000, 12, 12)


array([[[-5.58981257e-09,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -2.85005837e-09,  0.00000000e+00, ...,
          7.35581660e-07,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00, -2.41610476e-08, ...,
          7.35581660e-07,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         -1.73222756e-06,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          7.35581660e-07, -2.06936902e-08,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          7.35581660e-07,  0.00000000e+00, -5.16076197e-08]],

       [[-5.72838454e-09,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -2.82683425e-09,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e

In [14]:
e = np.load('ecological-modeling/n_clusters.npy')
print(e.shape)
e

(95000,)


array([4, 4, 4, ..., 6, 6, 6])

In [20]:
f = np.load('ecological-modeling/perturbations.npz')
# print(f.shape)
print(f['HF/HS'].shape)
f['HF/HS']

(95000, 12)


array([[ 0.        , -0.82049361, -0.82049361, ...,  0.        ,
        -0.82049361, -0.82049361],
       [ 0.        , -0.75314908, -0.97209465, ...,  0.        ,
        -0.75314908, -0.75314908],
       [ 0.        , -0.76882466, -0.98748759, ...,  0.        ,
        -0.76882466, -0.76882466],
       ...,
       [ 0.        , -1.19303209, -1.19303209, ...,  0.        ,
        -1.19303209, -1.19303209],
       [ 0.        , -1.17646032, -1.17646032, ...,  0.        ,
        -1.17646032, -1.17646032],
       [ 0.        , -1.14863886, -1.14863886, ...,  0.        ,
        -1.14863886, -1.14863886]])