In [2]:
import mdsine2 as md2
from mdsine2.names import STRNAMES
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
import os
import pandas as pd
from pathlib import Path
import matplotlib.cm as cm
import seaborn as sns

md2.visualization.set_perturbation_color('gray')
cols = [cm.tab10(i) for i in range(10)]
cols.append(cm.Set2(5))
cols.append(cm.Paired(4))

[DEBUG] Using default logger (stdout, stderr).


In [19]:
seeds = [0, 4, 27]
datasets = ['LF0', 'HF0']

In [20]:
output_dir_lf0 = Path('ecological-modeling/mcnulty-results/LF0/mdsine2')
output_dir_hf0 = Path('ecological-modeling/mcnulty-results/HF0/mdsine2')

In [60]:
lf0_s0 = pd.read_pickle(output_dir_lf0 / 'seed0' / 'mcmc.pkl')
lf0_s4 = pd.read_pickle(output_dir_lf0 / 'seed4' / 'mcmc.pkl')
lf0_s27 = pd.read_pickle(output_dir_lf0 / 'seed27' / 'mcmc.pkl')
hf0_s0 = pd.read_pickle(output_dir_hf0 / 'seed0' / 'mcmc.pkl')
hf0_s4 = pd.read_pickle(output_dir_hf0 / 'seed4' / 'mcmc.pkl')
hf0_s27 = pd.read_pickle(output_dir_hf0 / 'seed27' / 'mcmc.pkl')

In [90]:
# Calculate the rhat statistic- It assesses mixing of the chains {pylab/inference.py}
chains_lf0 = [lf0_s0, lf0_s4, lf0_s27]
chains_hf0 = [hf0_s0, hf0_s4, hf0_s27]

def shrink_factor_growth(chains, window, vname):
    for i in range(len(chains[0].graph[vname].value)):
        r_hat_window = []
        for j in range(np.around(chains[0].n_samples/window).astype(int)):
            np.array(r_hat_window.append(md2.pylab.inference.r_hat(chains, start=j, end=i+window, vname=vname)[:,i]))
            plt.plot(r_hat_window)
            plt.xlabel('Window')
            plt.ylabel('Rhat')
            plt.title(f'Rhat {chains[i].graph[vname].name}')
            plt.savefig(f'ecological-modeling/mcnulty-results/LF0/{chains[i].graph[vname].name}_rhat.png', dpi=300)
    return f'done'

In [91]:
plt.plot(shrink_factor(chains_hf0, 100, STRNAMES.GROWTH_VALUE))
plt.show()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [79]:
lf0_s0.graph[STRNAMES.GLV_PARAMETERS].growth.value

array([3.06026708e-01, 3.83789238e-01, 7.22364814e-01, 5.78800277e-01,
       2.30614016e-01, 3.26282865e-01, 3.37784800e-01, 4.03833770e-01,
       1.27126807e-01, 6.72626638e-04, 4.62764976e-01, 7.90852524e-01])

In [80]:
lf0_s0.graph[STRNAMES.GLV_PARAMETERS].self_interactions.value

array([5.94989880e-02, 3.78300911e-02, 2.53290411e-01, 1.65138153e-01,
       1.36670604e-01, 5.10607191e-02, 2.29503409e+00, 7.94185583e-01,
       4.70806140e+00, 4.37970179e+01, 3.22784685e-01, 5.76078238e-01])

In [81]:
lf0_s0.graph[STRNAMES.GLV_PARAMETERS].interactions.value

array([0.00734906])

In [82]:
lf0_s0.graph[STRNAMES.GLV_PARAMETERS].pert_mag.value

array([-0.91439782])

In [85]:
shrink_factor(chains_lf0, 100, STRNAMES.GROWTH_VALUE)


TypeError: 'int' object is not iterable